### ISSUE TITLE
Add support for python 3.10

### ISSUE THREAD

**Issue by ucyo** [imk-toolkit/imk-toolkit#36]
There seems to be a problem with `numpy` when executing `imktk` if it is running under `3.10`. 

Error message from CI/CD run [here](https://github.com/imk-toolkit/imk-toolkit/runs/4816902415?check_suite_focus=true)
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/work/imk-toolkit/imk-toolkit/imktk/imktk/__init__.py", line 2, in <module>
    from .toolkit import _add_folder
  File "/home/runner/work/imk-toolkit/imk-toolkit/imktk/imktk/toolkit.py", line 8, in <module>
    import xarray as xr
  File "/home/runner/work/imk-toolkit/imk-toolkit/imktk/.venv/lib/python3.10/site-packages/xarray/__init__.py", line 1, in <module>
    from . import testing, tutorial, ufuncs
  File "/home/runner/work/imk-toolkit/imk-toolkit/imktk/.venv/lib/python3.10/site-packages/xarray/testing.py", line 8, in <module>
    from xarray.core import duck_array_ops, formatting, utils
  File "/home/runner/work/imk-toolkit/imk-toolkit/imktk/.venv/lib/python3.10/site-packages/xarray/core/duck_array_ops.py", line 13, in <module>
    import pandas as pd
  File "/home/runner/work/imk-toolkit/imk-toolkit/imktk/.venv/lib/python3.10/site-packages/pandas/__init__.py", line 30, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
  File "/home/runner/work/imk-toolkit/imk-toolkit/imktk/.venv/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "pandas/_libs/interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Error: Process completed with exit code 1.
```
For now support for 3.10 is disabled.

**Comment by rcaspart** [comment]
You are using an "too old" version of numpy for python 3.10. It requires at least 1.21.3 (see https://github.com/numpy/numpy/releases/tag/v1.21.3) and you are using 1.21.1.

Depending on your requirements, it might be worth to look into the [oldest-supported-numpy meta-package](https://pypi.org/project/oldest-supported-numpy/), which is commonly used to avoid these kinds of problems.

**Comment by ucyo** [comment]
Hmm. That package looks interesting. But I am not sure if this is the solution for this. My concerns are (sorted and starting with most important) :

- Using different library versions (especially binaries like numpy) across different Python environments. The goal would be to use the same library version for all Python environments
- Poetry is doing the heavy lifting with the dependency management. I don't feel comfortable with interfering in this process for the single benefit of Python 3.10 support
- Weird that [scipy](https://github.com/scipy/scipy/blob/main/pyproject.toml#L19) itself is not using their own solution

**Comment by rcaspart** [comment]
The reason poetry is not doing what you expect it to in this case, is the design of poetry. With the initial call the file [`poetry.lock`](https://github.com/imk-toolkit/imk-toolkit/blob/master/poetry.lock) is created. It contains fixed versions for all dependencies, which poetry will not change unless specifically instructed to do so (see e.g. the [poetry documentation](https://python-poetry.org/docs/basic-usage/#updating-dependencies-to-their-latest-versions)).
Whether updating all dependency versions is what you want to do is up to you.

**Comment by ucyo** [comment]
No. Actually `poetry` is doing exactly what I want. No update to dependencies, unless I say so 👑 And dependencies are set to minor versions. No breaking changes for sure and I can be sure that the environment will be the same for every instance.
